apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ include "scrape-stack.namespace" . }}
  labels:
    {{- include "scrape-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.credentials.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
