# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: permit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'permit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpermit.proto\x12\x06permit\"i\n\rClientMessage\x12(\n\x07request\x18\x01 \x01(\x0b\x32\x15.permit.PermitRequestH\x00\x12#\n\x03ret\x18\x02 \x01(\x0b\x32\x14.permit.PermitReturnH\x00\x42\t\n\x07payload\"f\n\rServerMessage\x12$\n\x05grant\x18\x01 \x01(\x0b\x32\x13.permit.PermitGrantH\x00\x12$\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x13.permit.ServerErrorH\x00\x42\t\n\x07payload\"/\n\rPermitRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x0e\n\x06req_id\x18\x02 \x01(\x03\"@\n\x0bPermitGrant\x12\x11\n\tpermit_id\x18\x01 \x01(\t\x12\x0e\n\x06req_id\x18\x02 \x01(\x03\x12\x0e\n\x06ttl_ms\x18\x03 \x01(\x05\"6\n\x0cPermitReturn\x12\x11\n\tpermit_id\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\".\n\x0bServerError\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t2Q\n\rPermitService\x12@\n\x0cPermitStream\x12\x15.permit.ClientMessage\x1a\x15.permit.ServerMessage(\x01\x30\x01\x42\'Z%github.com/dwilson/request-auth/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'permit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%github.com/dwilson/request-auth/proto'
  _globals['_CLIENTMESSAGE']._serialized_start=24
  _globals['_CLIENTMESSAGE']._serialized_end=129
  _globals['_SERVERMESSAGE']._serialized_start=131
  _globals['_SERVERMESSAGE']._serialized_end=233
  _globals['_PERMITREQUEST']._serialized_start=235
  _globals['_PERMITREQUEST']._serialized_end=282
  _globals['_PERMITGRANT']._serialized_start=284
  _globals['_PERMITGRANT']._serialized_end=348
  _globals['_PERMITRETURN']._serialized_start=350
  _globals['_PERMITRETURN']._serialized_end=404
  _globals['_SERVERERROR']._serialized_start=406
  _globals['_SERVERERROR']._serialized_end=452
  _globals['_PERMITSERVICE']._serialized_start=454
  _globals['_PERMITSERVICE']._serialized_end=535
# @@protoc_insertion_point(module_scope)
