apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: scrapestack  # change to scrapestack-dev for dev
type: Opaque
stringData:
  POSTGRES_USER: scrapestack
  POSTGRES_PASSWORD: your-password-here
